server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://192.168.3.1:3306/403forbidden
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    solr:
      zk-host: 192.168.3.1:2182,192.168.3.1:2183,192.168.3.1:2184
#
##----------- solr config ----------------
#solr:
#  zk:
#    host: 192.168.3.1:2182，192.168.3.1:2183，192.168.3.1:2184
#  collection:
#    name: mycollection
