server:
  # 服务端口
  port: 7777
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.3.1:3306/403forbidden?serverTimezone=GMT%2B8&useSSL=true
    username: root
    password: 123456789
  application:
    name: demo-provider
# dubbo 相关配置(dubbo 的配置不再以 Spring 开头)
dubbo:
  application:
    # 应用名称
    name: demo-provider
  scan:
    # 接口实现者（服务实现）包
    base-packages: com.example.demo.service.impl
  # 注册中心信息
  registry:
    address: zookeeper://192.168.3.1:2181
  protocol:
    # 协议名称
    name: dubbo
    # 协议端口
    port: 20880
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.pojo