server:
#  address: 192.168.3.1
  port: 8080
#  servlet:
#    context-path: /
dubbo:
  application:
    name: demo-web
  registry:
#    address: zookeeper://192.168.3.1:2181?backup=192.168.3.1:2181,192.168.2.53:2181
    address: zookeeper://192.168.3.1:2181
    timeout: 5000
  consumer:
    timeout: 50000
#配置springboot热部署
spring:
  application:
    name: demo-web
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.3.1:3306/403forbidden?serverTimezone=GMT%2B8&useSSL=true
    username: root
    password: 123456789
  devtools:
    livereload:
      port: 35738
#    restart:
#      enabled: true
#      #设置重启目录
#      additional-paths: src/main/java
#      exclude: WEB-INF/**
  freemarker:
    cache: false  #页面不加载缓存,修改及时生效
  #配置静态资源的访问路径(注意区分存放路径)
  mvc:
    static-path-pattern: //**
  #配置静态资源的存放路径
  resources:
    static-locations: classpath:/static
